### ISSUE TITLE
What's the spec of field_algebra?

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#10]
I added a version of `common_denominator` that is faster and cleaner; it does not perform simplification in portions of the term that it doesn't need to. (https://github.com/mit-plv/fiat-crypto/commit/2b7e45498d3a3e8856906c7eed7caec4f0053aae)

However, I can't use it in `field_algebra`, because various code depends on the exact way in which `field_algebra` calls `field_simplify_eq`.  If we can, I'd like to head off this issue early; this is the first hint of something like the design flaw in Coq's unification where the devs can't touch anything without breaking backwards compatibility, because they've extended it ad-hoc without any specification.

(@andres-erbsen @achlipala)

**Comment by andres-erbsen** [comment]
If we find a way to implement this, `field_algebra` should not touch the hypotheses at all. It should either solve the goal completely, or leave behind goals of the form `not (equiv ?x 0)`. It should solve all goals that are implied by Nullstellensatz alone, which in an algebraically closed field is all implications between equalities. We should probably rename it to `field_equalities` or something like that.

There also should be a tactic that brings all hypotheses to a common denominator the obvious way, with otherwise minimal intervention.

Neither of these tactics or their combination would solve the goals that are currently solved due to the effects `field_algebra` calling `field_simplify_eq` has. In the short term, we could call field simplify manually in those cases -- arbitrarily brittle automation is no better than no automation.

In longer term, it would be nice to have a `solve_for expr1 expr2...` tactic that behaved like Sage's `solve(list_of_hypotheses, [expr1, expr2...])` on abstract fields. I am not sure how general could make it, ideally it would produce for each `expr` any equality with the given LHS that `field_algebra` could prove. Less ambitiously, we could have `solve_for expr in hyp` which would produce an equality if it can be reached by associativity, commutativity, distributivity, and applying invertible operations to both sides.

In very the long term, we would have unification modulo field laws, like SymPy does, and applying lemmas that don't quite match definitionally wouldn't require explicit algebraic manipulation at all.

The reality is that while I can postulate these specifications here, trying to implement them would cause me to stall and think for quite a while before even knowing how much work it would be. Implementing powerful algebraic manipulations is far from trivial. Coming up with a less powerful but non-arbitrary spec is not necessarily easier.

**Comment by JasonGross** [comment]
> by Nullstellensatz alone, which in an algebraically closed field is all implications between equalities

Does this include polynomial fractions?

Note that Nullstellensatz, with a tiny bit of wrapping, can also prove all implications between inequalities: we have `a * b <> 0 <-> (a <> 0 /\ b <> 0)`, hence we can combine all hypothesis inequalities into a single equation.  Then it suffices to solve goals of the form `a = 0 -> b = 0 -> ... -> c = 0 -> d <> 0 -> e <> 0`.  This is true iff `a = 0 -> b = 0 -> ... -> c = 0 -> e = 0 -> d = 0` (`intro; apply (_ : d <> 0)`), which is a goal that `nsatz` should be able to handle.

>  brings all hypotheses to a common denominator the obvious way

So would `a / (b * c) + d / b = e` become `a + d * c = e * b * c` (hard) or `a * b + d * b * c = e * b * b * c` (easier)?

**Comment by andres-erbsen** [comment]
Yes. Rational functions can be rewritten to polynomial equations by bringing everything to a common denominator. New goals would be generated for whatever needs to be nonzero.

The strategy for proving inequalities sounds good. In case it fails to solve all nonzero conditions, we should still leave subgoals instead of failing -- users can write `solve [ ... ]` if they need to, and the goals can be discharged using lemmas that are not purely due to field structure.

The easier equation for common denominators is fine -- if we want to make sure that there are no terms that can be factored out of all addends, that can be a separate tactic, a multi-addend version of the `mul_cancel_l` lemma. The process I have in mind for common denominator is repeated application of the following rules:

    a/b + c/d -> (a*d + b*c)/(b*d)
    a/b * c/d -> a*c/(b*d)
    a/b = c/d -> a*d = b*d

**Comment by JasonGross** [comment]
I've made [a Coq Enhancement Proposal](https://github.com/coq/ceps/pull/4) for handling inequalities in the standard library `nsatz`.  This made me realize that there's one case that `super_nsatz` currently doesn't handle, even though it perhaps should:
```coq
Goal forall x y : F, x^2 = y^2 -> x <> y -> x = -y.
```
The way to handle this goal is to `destruct (x =? -y) eqn:?; [ assumption | super_nsatz ]`.  I've just pushed a commit that fixes this deficiency.

The common denominator generating code is still a mess, and sometimes slow, unfortunately.  There's also the unfortunate fact that bringing everything to common denominators can make a previously solvable goal unsolvable (if the context contained irrelevant division by zero).  How should we handle this case?
