### ISSUE TITLE
incremental builds across submodules

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#1372]
It'd be great if changing a file in coqutil/bedrock2/rupicola and then calling `make` automatically rebuilt the appropriate fiat-crypto files. @samuelgruetter says that the way he's using `-Q` instead of `COQPATH` in bedrock2 allows for incremental builds across submodules and seems to work fine.

**Comment by samuelgruetter** [comment]
I tried it out in [this commit](https://github.com/mit-plv/fiat-crypto/commit/c8da1daed9c73a0a5b7b8a84cb650fcc7d63c9d8). The crucial difference is that `.Makefile-coq.d` now also contains dependencies on the files in submodules, so if a file in the rupicola or bedrock2 submodule is modified, fiat-crypto's make knows which files in fiat-crypto it has to recompile because of the submodule changes.
I don't know what other use cases I broke with that change, so I didn't make a pull request, but some guidance by @JasonGross regarding how badly this change breaks build processes that I'm not aware of would be appreciated :slightly_smiling_face:

**Comment by andres-erbsen** [comment]
The builds are now incremental but not fine-grained.
