### ISSUE TITLE
Failing in coq CI

### ISSUE THREAD

**Issue by SkySkimmer** [mit-plv/fiat-crypto#1387]
https://gitlab.com/coq/coq/-/jobs/3103768235

**Comment by andres-erbsen** [comment]
This fixed by the merge of https://github.com/mit-plv/fiat-crypto/pull/1361 which updated fiat-crypto to work with rewriter HEAD. This mattered because Coq CI [ignores](https://github.com/coq/coq/blob/7fc6722c9f4eef7af37d752fd6e4cb604f9ba9ed/dev/ci/ci-fiat_crypto_ocaml.sh#L13) the rewriter version pin in fiat-crypto, whereas our own CI [passed](https://github.com/mit-plv/fiat-crypto/actions/runs/3130972619/jobs/5081816743) the same commit with a pinned compatible rewriter.
