### ISSUE TITLE
Installation problems on Arch Linux: Package `coq-core.plugins.ltac' not found

### ISSUE THREAD

**Issue by defeo** [mit-plv/fiat-crypto#1787]
I get the same error as #1558 when compiling on Arch:

```
CAMLC -c src/Rewriter/Util/plugins/ltac2_extra.mli
ocamlfind: Package `coq-core.plugins.ltac' not found
```

`coq` and `ocaml-findlib` installed through `pacman`.

Any ideas?

**Comment by JasonGross** [comment]
Looks like Arch recently upgraded their Coq package from 8.16 to 8.18, so I suspect the issue is that the META file is going misplaced in the Arch package. https://github.com/coq/coq/issues/15635 might have more hints, and Coq Zulip is probably a good place to ask for help on how the Arch package should be fixed.  (In the meantime, you can use the same workaround as in #1558 and install Coq via opam)

**Comment by JasonGross** [comment]
Plausibly related: https://github.com/coq/coq/issues/15663

**Comment by JasonGross** [comment]
I guess the issue in Arch is a missing configure at https://gitlab.archlinux.org/archlinux/packaging/packages/coq/-/blob/main/PKGBUILD?ref_type=heads#L49 as in https://github.com/coq/coq/issues/15663#issuecomment-1654496159

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/15635#issuecomment-1866724665_

I will email the Arch maintainer about this

**Comment by JasonGross** [comment]
You might be able to work around the issue with
```
ln -s /usr/lib/coq /usr/lib/ocaml/coq
ln -s /usr/lib/coq-core /usr/lib/ocaml/coq-core
ln -s /usr/lib/coqide-server /usr/lib/ocaml/coqide-server
```

**Comment by defeo** [comment]
Wow! Thanks for the help, I couldn't hope for better assistance!

The symlinks indeed worked. I guess I can close this.
