### ISSUE TITLE
Prove is_bounded_by -> small

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#211]
I need a lemma that says
```coq
forall sz r v, Crypto.Util.ZRange.is_bounded_by None (Tuple.repeat {| lower := 0 ; upper := r - 1 |} sz) v -> Saturated.small r v
```

You may or may not want to do this by defining `small` to be `is_bounded_by`.

**Comment by jadephilipoom** [comment]
Why do we need this exactly?

**Comment by JasonGross** [comment]
The reflective pipeline deals in bounded words.  We need to show that every bounded word is automatically small.  I think it's nicer to do this once than to have to do it manually and separately for each limb of each bounded word.

I think either `small ` should be replaced by `ZRange.is_bounded_by`, or `Tuple.v` should get a lemma to convert between `fieldwise` and `List.In`, and that lemma can be used directly.  (Idk if API should get an `unfold_small` lemma proven by `reflexively`, or if I should just `unfold small`.)

I'm happy to take this on my plate, and either make a PR that does the first, or push the lens to do the second.

**Comment by jadephilipoom** [comment]
Okay, this doesn't really belong in `Saturated`, but I don't have better ideas of where to put it. I think you should do it, since I am currently working on `conditional_sub` and don't have that much spare time--you will probably get to it first. I feel very unenthusiastic about replacing `small` with `is_bounded_by`, which I have found unwieldy to work with in the past. But proving a lemma that matches up the two of them is fine and shouldn't be hard.

**Comment by JasonGross** [comment]
Proven in `ZRange.v`
