### ISSUE TITLE
rewrite addcarry 0 + x + (- carry) to subborrow x - 0 - carry

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#223]
As in https://github.com/mit-plv/fiat-crypto/commit/0a74b3cee39f5cc909471e86652996f63455a0d6#diff-fb0db573d8885dd70e8292403ae7e6efR108 . In particular, I think

    ℤ x316 = Op (Syntax.Opp (Syntax.TWord 3) Syntax.TZ) (Return x315);
    uint64_t _, ℤ x319 = addcarryx_u64ℤ(0x0, x316, x303);

should become

    uint64_t _, ℤ x319 = subborrowx_u64ℤ(x316, 0x0, x315);

**Comment by JasonGross** [comment]
Uhhhhhhhh, this is very sketchy.  First, your transformation is mathematically invalid, because you drop `x303` and duplicate `x315`/`x316`.  Second, I can't actually recognize the carry bit, so the transformation would actually be
`-x + y + 0`
~~~>
`y - 0 - x`
where `x` is assumed to be a carry bit just because it's negative and the current carry bit is zero and the other argument is not known to be negative, and this seems extremely fragile.  Do you still want me to implement this?

**Comment by andres-erbsen** [comment]
I dont understand what you mean by mechanically invalid. Yes, there are some implicit side conditions, but I am not sure what restrictions I am supposed to be working around. Not being able to detect carry bits is already serious enough.

**Comment by JasonGross** [comment]
I mean that I think you made a typo: under most conditions, `0 + -x315 + x303` is not the same as `-x315 - 0 - x315`; in particular, `x303` appears in one and not the other.

**Comment by JasonGross** [comment]
This will be obsoleted by #226.
