### ISSUE TITLE
Renaming sz to numlimbs breaks reification

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#239]
If I rename sz to numlimbs in src/ArithmeticSynthesisTest.v, and then create Definition sz := numlimbs, reification fails with error message terms that look like they should reify. https://gist.github.com/andres-erbsen/40147c552f912f09cb210542eb1f8b9a

**Comment by JasonGross** [comment]
Note that [`sz` appears explicitly in lists of things that are unfolded](https://github.com/mit-plv/fiat-crypto/blob/master/src/Specific/IntegrationTestSub.v#L60).  If you alias it to something, you need to add that something to the list.  Or we need to find another way to guarantee its unfolding; basically, the issue is that `tuple` needs to fully reduce, so it can't be blocked on an identifier.  I could possibly make `Pipeline.ReflectiveTactics.do_reify` stronger, e.g., with something like
```coq
repeat match goal with
       | [ |- context[Tuple.tuple' _ ?n] ] => progress cbv beta iota delta [n] in *
       | [ H : context[Tuple.tuple' _ ?n] |- _ ] => progress cbv beta iota delta [n] in *
       | [ |- context[Tuple.tuple _ ?n] ] => progress cbv beta iota delta [n] in *
       | [ H : context[Tuple.tuple _ ?n] |- _ ] => progress cbv beta iota delta [n] in *
       end.
```
(or maybe `let n' := (eval vm_compute in n) in progress change n with n' in *` instead of `cbv ...`).... Do you want me to do this?
