### ISSUE TITLE
Separate Makefile targets for library and generated code

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#27]
As the `Specific/` code becomes more developed, build times go up. It woud be nice to have Makefile target that builds everything but the `Specific` directory for use while pushing changes through the rest of the codebase. This would be especially useful when refactoring irrelevant proofs.

**Comment by JasonGross** [comment]
Are we okay with depending on the submodule for building?  I have some makefile scripts there that make this significantly easier and nicer (handle things like making it so our `clean` target doesn't get clobbered by the `clean` target of `Makefile.coq` when we `-include Makefile.coq` to get the list of `VOFILES` so that we can find which ones live in `Specific`), and will give us some other nice things (such as early errors when we forget to include something in `_CoqProject`).

**Comment by andres-erbsen** [comment]
I don't have any specific insight here. I think we can use the submodule if you think this is a good idea. I myself probably wouldn't. In any case, if you end up doing something that means that somebody else on this project would fail to build the code after `git pull`, I think it would be a good idea to send out an email.

**Comment by JasonGross** [comment]
Because the code I'm reusing messes with `coq_makefile` and makes `clean` a double-colon rule, the project fails to build after `git pull` if you have the old `Makefile.coq` lying around (in fact, `make clean` already fails).  I don't see any way to get around this other than writing hacky code that looks at the current contents of `Makefile.coq` and sets the `clean` target appropriately...  I'll send an email if #30 works for you.
