### ISSUE TITLE
do we still need RewriteAddToAdcInterp?

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#323]
re https://github.com/coq/coq/pull/6935 and https://travis-ci.org/SkySkimmer/coq/jobs/349796288

perhaps we can just remove `RewriteAddToAdcInterp` to give coqdevs some slack on this one? I don't think we were ever happy with what that file did, and after @jadephilipoom implemented MontgomeryAPI, is it even used right now? Regardless, the experimental pipeline won't have anything like that (but we probably should not arbitrarily axe old stuff before it has proofs done?)

**Comment by JasonGross** [comment]
"Give the coqdevs some slack on this one" is not a good reason to remove this file.  This seems like fiat-crypto is pulling its weight as a CI target.  That PR makes the peak memory usage of `RewriteAddToAdcInterp` jump from 932 328 ko to > 5 922 896 ko, and a 6x increase in memory usage, even in corner cases, seems like exactly the kind of thing we want coqdevs to accept only after careful deliberation.

**Comment by JasonGross** [comment]
In fact, before removing the old stuff, we might want to make a legacy branch, and have Coq continue testing the old pipeline *because* it stresses so much of the system.

**Comment by andres-erbsen** [comment]
Hmm, yeah, I can see that way of interpreting the situation. I think the implicit difference here whether we think the particular things that are putting stress on the coq implementation are things that it is worthwhile to put in effort to support. I agree that if the slowdown is just because we trigger a rare case of a critical primitive, it should be fixed. On the other hand, we also do obscure and weird things with Coq sometime (especially Ltac), and I think it would be reasonable to drop some of them (the same way i think coinductives are best removed).

**Comment by JasonGross** [comment]
My bar is roughly "if the coqdevs can add a comment in the source code specifying where the performance tradeoff is (e.g., 'doing this this way instead of that way incurs such-and-such an overhead in such-and-such cases because of such-and-such a reason, but we do it anyway because simplicity (or whatever)'), and they add a line to `CHANGES` mentioning the performance regression, then I'm fine with dropping the test.  But my sense is that most performance regressions in Coq are unexpected and hard to diagnose, and aren't actually intended as trade-offs.
