### ISSUE TITLE
Error compiling `Cannot find a physical path bound to logical path matching suffix`

### ISSUE THREAD

**Issue by elichai** [mit-plv/fiat-crypto#673]
Compiler output:
```
$ make
make --no-print-directory -C rewriter
make[2]: Nothing to be done for 'real-all'.
make --no-print-directory -C bedrock2/deps/coqutil
Generating Makefile.coq.all
make -f Makefile.coq.all
make[3]: Nothing to be done for 'real-all'.
make --no-print-directory -C bedrock2/bedrock2 noex
Generating Makefile.coq.noex
rm -f .coqdeps.d
make -f Makefile.coq.noex
make[3]: Nothing to be done for 'real-all'.
make --no-print-directory -C coqprime src/Coqprime/PrimalityTest/Zp.vo
make[1]: 'src/Coqprime/PrimalityTest/Zp.vo' is up to date.
COQC src/Util/LetIn.v
File "./src/Util/LetIn.v", line 5, characters 8-27:
Error: Cannot find a physical path bound to logical path matching suffix
Rewriter.Util.

make: *** [Makefile.coq:678: src/Util/LetIn.vo] Error 1
```

Status:
```
$ git log -1
commit 3290d24ced2c3b08692cee7ca8df684b7711724e (HEAD -> master, origin/master, origin/HEAD)
Author: Jade Philipoom <jadep@mit.edu>
Date:   Fri Mar 6 15:10:12 2020 -0500

    move lemmas to better locations
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Coq version:
```
$ coqc -v
The Coq Proof Assistant, version 8.11.0 (January 2020)
compiled on Jan 28 2020 22:33:30 with OCaml 4.09.0
$ uname -a
Linux nphard-core 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux
```

**Comment by jadephilipoom** [comment]
Investigating. Looks like for some reason it's having a problem with the rewriter dependency, but I'm not currently managing to replicate the issue, even with the exact same Coq subversion.

Can you show the output of the following:
`git submodule status`
`ls rewriter/src/Rewriter/Util`

If you've updated submodules recently, try `make clean-rewriter && make` to ensure the dependency has been refreshed.

**Comment by elichai** [comment]
> If you've updated submodules recently, try `make clean-rewriter && make` to ensure the dependency has been refreshed.

Running these did fix it. thanks. 
FYI is there a usage example somewhere to see that I understand the API correctly? thanks.

**Comment by jadephilipoom** [comment]
The README includes some usage examples for generating code (from either `src/ExtractionOcaml/` or `src/ExtractionHaskell`):

```
# Generate code for 2^255-19
./unsaturated_solinas '25519' '5' '2^255 - 19' '64' carry_mul carry_square carry_scmul121666 carry add sub opp selectznz to_bytes from_bytes > curve25519_64.c
./unsaturated_solinas '25519' '10' '2^255 - 19' '32' carry_mul carry_square carry_scmul121666 carry add sub opp selectznz to_bytes from_bytes > curve25519_32.c

# Generate code for NIST-P256 (2^256 - 2^224 + 2^192 + 2^96 - 1)
./word_by_word_montgomery 'p256' '2^256 - 2^224 + 2^192 + 2^96 - 1' '32' > p256_32.c
./word_by_word_montgomery 'p256' '2^256 - 2^224 + 2^192 + 2^96 - 1' '64' > p256_64.c
```

(The README doesn't go into a ton of detail, but the first command's arguments will generate code for the modulus 2^255 - 19 with 5 limbs and 64-bit integers, and it will generate the operations: `carry_mul carry_square carry_scmul121666 carry add sub opp selectznz to_bytes from_bytes`.)

Is that the API you're looking for?

**Comment by elichai** [comment]
> 
> Is that the API you're looking for?

I meant after I generate all the functions, like there's `fiat_p256_from_montgomery` but no `to_montogemery` function. like when should that be used (https://github.com/mit-plv/fiat-crypto/blob/master/p256_64.c#L915)

**Comment by jadephilipoom** [comment]
Ah. No, we don't currently have usage examples for the generated code, because the generated code is not really intended to be a full standalone library. It's intended to provide verified versions of the most complex operations. I'm guessing there's no `to_montgomery` because it's a simple operation (multiply by the montgomery `R` value that corresponds with your modulus). @JasonGross, do you have a more detailed answer?

**Comment by JasonGross** [comment]
We could add `to_montgomery` if you'd like (feel free to open an issue - it'd be pretty easy to add as `to_montgomey x := mulmod x R2mod` in WBW Montgomery in Arithmetic/).  We don't have it because [the BoringSSL code](https://boringssl.googlesource.com/boringssl/+/refs/heads/master/third_party/fiat/p256.c) doesn't use it, and no one else has asked for it.

As Jade said, we still hope to extend our library to handle curve-level operations, and not just field-level operations, which is the proper API.

We would still love to have tests, though, if you or anyone else wants to contribute them.  I'm continue to feel concerned about adding more backends workout testing my code that selects bitsize casts from knowledge of bounds.

**Comment by mimoo** [comment]
running into the same problem. Not sure why BoringSSL is implementing their own to_montgomery... I created an issue for that: https://github.com/mit-plv/fiat-crypto/issues/785

problems are:

* the R value is not displayed in the code generated, if I want to get it I need to reverse-engineer the REDC
* if I want to implement the modular multiplication with R, then what code do I even use in the first place :) I need another group arithmetic implementation
