### ISSUE TITLE
Add Rust tests to the CI

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#705]
It would be nice to make sure we don't break the Rust code.  In service of that, I'd like to figure out how to get the Rust code test-suite to run on the CI.  See https://github.com/mit-plv/fiat-crypto/pull/676#issuecomment-597724739 .  I'm thinking we can maybe make dalek-cryptography a submodule of fiat-crypto, or else clone it on the CI and adjust whatever needs to be adjusted to get it to run with the local copy of fiat-crypto.

cc @huitseeker @zoep

**Comment by huitseeker** [comment]
You would need to clone the calibra fork of curve25519_dalek:
https://github.com/calibra/curve25519-dalek/tree/fiat2 (note the branch)
in CI and run :
`cargo test --features="std fiat_u64_backend" --no-default-features `

Operating on the source dalek repo would require you to "plug in" fiat in the backend .. and that would be, at minima, precisely what the fork does.

/cc @isislovecruft

**Comment by JasonGross** [comment]
Thanks!  How do I tell it to use my local copy of fiat-crypto rather than the published one?  I assume I need to change the line in https://github.com/calibra/curve25519-dalek/blob/fiat2/Cargo.toml that says
```
fiat-crypto = { version = "0.1.0", optional = true}
```
Is there a way to give it a path, e.g., `/path/to/fiat-crypto/fiat-rust/`?

**Comment by huitseeker** [comment]
Plenty of ways!

You can [rewrite the dependency to point to the git directory](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) , which you probably want to do with a [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) statement you can `cat ... >> Cargo.toml` on build, but you can also use a [minor version in the present repo](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version)

**Comment by JasonGross** [comment]
Thanks!  I think I probably want to use `path` rather than `git`.  (Does it accept paths that are not subdirectories of the current directory, and/or absolute paths?)  And for the patch statement, do I want to use `patch.crates.io`?

**Comment by huitseeker** [comment]
The fork at https://github.com/calibra/curve25519-dalek/tree/fiat2 (please note the branch `fiat2`, which [must be reflected in the attributes of your dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)) is guaranteed to contain a maintained integration of fiat-crypto for a significant amount of the foreseeable future.

> Does it accept paths that are not subdirectories of the current directory, and/or absolute paths?
The `path` attribute supports both non-subdirectory relative paths and absolute paths.

> do I want to use patch.crates.io?

If you are modifying the `Cargo.toml` of the calibra/curve25519-dalek fork, since it fetches the fiat-crypto rust package from crates.io here:
https://github.com/calibra/curve25519-dalek/blob/b08488b5276908189d378bdcea9c8f2ea85b824a/Cargo.toml#L46
then yes, you do want to use `patch.crates.io`.
