### ISSUE TITLE
Arguments to definitions used in Experiments.Ed25519 vary with Coq versions

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#75]
The definitions and lemmas *used* (not defined) in Ed25519 take different arguments in different coq versions. I am guessing that this is similar to the issue we had with `Shrink Obligations` (discussed at
https://github.com/mit-plv/fiat-crypto/pull/57 and https://coq.inria.fr/bugs/show_bug.cgi?id=5044).

**Comment by JasonGross** [comment]
Here's one instance:

Quoting [the changelog](https://github.com/coq/coq/blob/trunk/CHANGES#L576):
> - Tactic "tauto" was exceptionally able to destruct other connectives
  than the binary connectives "and", "or", "prod", "sum", "iff". This
  non-uniform behavior has been fixed (bug #2680) and tauto is
  slightly weaker (possible source of incompatibilities). On the
  opposite side, new tactic "dtauto" is able to destruct any
  record-like inductive types, superseding the old version of "tauto".

You had an `Equivalence` in the context that `tauto` was destructing, but otherwise not using.  This made the proof pick up an extra dependency from the context in 8.4, but not 8.5/8.6.

**Comment by JasonGross** [comment]
Another issue is exactly that of https://github.com/mit-plv/fiat-crypto/pull/57#issuecomment-242510709.  I suggested removing the `pose proof` from `bash`, but it seems to still be there...

**Comment by JasonGross** [comment]
Closed by 4b3b69e
