### ISSUE TITLE
to_montgomery and feedback on rust code

### ISSUE THREAD

**Issue by mimoo** [mit-plv/fiat-crypto#785]
Hello hello.

As @elichai pointed out, there is no `to_montgomery` function produced which limits how fiat-crypto can be used. I'm currently implementing ECDSA with P-256 in Rust and was hopping to use fiat-crypto for this.

Some other feedback about the generated rust:

* documentation before a function should be using `//!` so that they are displayed when generating documentation (via `cargo doc`)
* most functions are not efficient at the moment because the input and the output needs to be two different bytearrays. Indeed in rust you cannot do something like:
  ```
  let a = [0u32; 4];
  operation(&mut a, &a);
  ```
  so to use the fiat operations I have to create a new bytearray to store the result every time. This might get optimized out by the compiler but I'm not sure. I have no real short-term solution here, but an idea would be to provide two different APIs: one that provide the result in place (and for this to happen all functions need to be implemented as methods on a wrapper struct), and the current one.

**Comment by JasonGross** [comment]
> As @elichai pointed out, there is no `to_montgomery`

Should be fixed by #786, see also #784.

> * documentation before a function should be using `//!` so that they are displayed when generating documentation (via `cargo doc`)

I'll make a PR for this, thanks.

>  This might get optimized out by the compiler but I'm not sure

Can you check?  It seems like the compiler should be able to optimize this out; the functions are all declared `#[inline]`, and don't assign to the output until the very end of the function, so it seems like if you define your own wrapper function for each of these, that just allocates the temporary arrays and does copying and then calls the fiat-crypto inline functions, the compiler should be able to optimize out the intermediate allocation.  (And, if not, this seems like it should be a request for the Rust compiler, not for fiat-crypto.)

**Comment by JasonGross** [comment]
I'm going to consider this issue closed with the merging of #787.  I'll draft a new release now.  Feel free to open a new issue about wrapper methods if you want to, and think it should be something we handled rather than having the Rust compiler handling.
