### ISSUE TITLE
Mysterious MacOS build failure?

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#818]
In #817, the MacOS build succeeded on push, but consistently fails in the job called on pull request (after a very short time, with no error message). All other builds succeed. Not sure what to make of this. @JasonGross , thoughts?

**Comment by JasonGross** [comment]
When was this run?  The GH Actions people claim at https://github.com/actions/virtual-environments/issues/736#issuecomment-648192897 to have fixed yesterday (June 23) an issue causing MacOS builds running between 1:00-2:00 AM UTC to fail due to configuration errors.  If this failure is more recent than that, or happened outside of the 1--2 am UTC range, we should report it on that issue.

**Comment by jadephilipoom** [comment]
I definitely ran it at least once outside that time range. How can we be sure it's their problem, though?

**Comment by JasonGross** [comment]
The fact that the build log displays all red x's rather than one red x and subsequent cancellation marks is an indication that it's a problem on their side, as I described in the initial comment on that issue report.  I've posted another comment at https://github.com/actions/virtual-environments/issues/736#issuecomment-648928937 reporting this particular failure

**Comment by JasonGross** [comment]
Haven't seen this recently, so going to close it for now
